image: node:24

pages:
  stage: build
  cache:
    key:
      files:
        - web/package-lock.json
    paths:
      - web/.npm/
  script:
    - cd web
    - npm ci --cache .npm --prefer-offline
    - WIKI_BASE=/$CI_PROJECT_NAME/ npm run build
    - WIKI_BASE=/$CI_PROJECT_NAME/ npm run check
    - mv dist ../public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never # 既定ブランチ以外ではジョブを走らせない
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
